const BlogApi = [
  {
    id: 1,
    image: "./images/6.jpg",
    date: " 18 November 2022",
    title_one: "Using type-2 fuzzy ontology to improve semantic interoperability for healthcare and diagnosis of depression.",
    desc_one: "Abolfazl Ghorbani, Fatemeh Davoodi, Kamran Zamanifar ",
    title_two: "ABSTRACT",
    desc_two: "Ontology enhances semantic interoperability through integrating health data from heterogeneous sources and sharing information in a meaningful way. In the field of smart health services, semantic interoperability means the exchange and interpretation of data without ambiguity and uncertainty. However, existing classical ontologies are not able to represent vague and uncertain knowledge, especially in contexts of mental health disorders which are associated with varying degrees of uncertainty and inaccuracy of diagnosis, and in this case, the treatment is a complex and common mental process necessitating to share information accurately and unambiguously. Type-2 fuzzy set theory can offer a fruitful solution in order to control uncertainty or express ambiguous concepts in a dynamic and complex environment such as healthcare systems. Herein, a semantic framework for healthcare, and also monitoring mental health disorders using type-2 fuzzy set theory based on the Internet of Thing (IoT) is suggested, in which all depression-related concepts are semantically annotated to share detailed information with the treatment staff. This framework not only paved the way to increasing the accuracy of medical diagnosis and decision-making but also provides the possibility of inference and semantic reasoning using the languages of SPARQL query and DL query. ",
    title_three: "Conclusions and future work.",
    desc_three: "In this paper, we proposed a semantic framework using IoT-based type-2 fuzzy ontology for healthcare and mental health monitoring. In this system, the type-2 fuzzy logic theory is used to represent the inevitable uncertainties regarding the parameters of depression. Due to the use of semantic technology and type-2 fuzzy logic, the proposed method has improved the ability of semantic reasoning in retrieving query information; it has also made it possible to use expressive query languages, such as SPARQL and DL query to retrieve information. Given alarming reports of increasing prevalence of depression, especially during the corona pandemic situation, and conditions related to stress and social isolation, serious measures to diagnose and treat depression are increasingly required. Hence, using smart health technologies to help patients is the subject of increasing interest. In this regard, several experiments in the form of questions and answers have been performed to test the efficiency of the proposed system. We used both Cohen's Kappa and confusion matrix methods for evaluation of our proposed system. The Cohen's Kappa method confirm the agreement of our results with the expert statements. The results of confusion matrix method confirm     the improvement ability of our system compared to classical ontologies to represent knowledge and extract information from blurred data. The proposed framework can be considered as a powerful model to improve the accuracy of medical diagnosis and medical decision-making and can be used as a basis for knowledge sharing between humans and machines. As future work, we will reduce the volume of rules and regulations in the ontology rules database, select more effective rules in output production, and increase the accuracy in the performance of the propose, system using fuzzy analytic hierarchy process. Hence, the base ontology will be constantly improved with new knowledge to assist mental health professionals in clinical decisions which pay a way to optimize processes, minimize mental health diseases diagnosis time, and profit mental health professionals. ",
     link: "https://doi.org/10.1016/j.artmed.2022.102452 ",
    publicher: "0933-3657/© 2022 Published by Elsevier B.V."
  },
  {
    id: 2,
    image: "./images/7.jpg",
    date: " 28 February 2022",
    title_one: "Type-2 fuzzy ontology-based semantic knowledge for indoor air quality assessment. ",
    desc_one: "Abolfazl Ghorbani, Kamran Zamanifar",
    title_two: "ABSTRACT",
    desc_two: "Semantic web technology plays an increasing role in performing smart home applied programs and it has led to improve semantic interoperability among different systems. However, classical ontologies fail to illustrate ambiguous, incomplete, and uncertain knowledge often available in the real world.On the other hand, the air quality assessment carried out to determine ‘‘the degree of pollution’’ lacks accurately specified boundaries; therefore, the conventional approach based on classic ontology cannot extract real-valued memberships and consequently fails to support ambiguous, incomplete, and uncertain knowledge. Integrating semantic web of things technology (SWOT) and type-2 fuzzy logic improves the capability of semantic reasoning to retrieve query information. Annotation of sensor generated data and the ability to infer and represent knowledge based on type-2 fuzzy logic are extremely essential when the available data are ambiguous and uncertain. Hence, in this paper, we have provided a framework to build an IoT-based home air quality assessment system by using type-2 fuzzy ontology so that smart home systems can make a decision and control appropriately based on redefined rules by employing the provided semantic reasoning.",
    title_three: "Conclusions and future work.",
    desc_three: "In this paper, we presented a new IoT-based method to assess indoor air quality. As in complex dynamic areas including ‘‘air pollution assessment’’ data are extremely blurred and vague and classical ontology is unable to manage the ambiguous knowledge,hence, type-2 fuzzy set theory was employed to express the ambiguity and describe vague data. The proposed method improves semantic reasonability in query information retrieval thanks to using semantic technology and type-2 fuzzy logic and makes it possible to utilize a strong query language like SPARQL to retrieve information. Also, by utilizing the semantic reasonability provided in the proposed model as well as annotation of sensor’s raw data and integration of the same into background knowledge, smart home systems can take controlling or preventive actions to reduce indoor air pollution and inform the residents of the current air quality based on the rules and regulations defined in the ontology knowledge base and according to current circumstances and the severity of air pollution. The latest scientific findings have indicated that the risk of getting coronavirus infection from surfaces is as low as 1 in 10 000, the virus is mainly transmitted via the air, and being exposed to unhealthy air is associated with an increased risk of COVID-19-related death [1]. Therefore, it is,vital to apply smart programs to control and monitor indoor air quality for helping patients and sensitive groups. Multiple tests have been carried out to evaluate the efficiency of the system, the results of which indicate accuracy in knowledge representation and semantic reasoning based on type-2 fuzzy logic. The proposed system can be considered as a powerful model for smart home programs. We have many relevant works to do in the future,including Considering different weights for air pollutants in the ontology that can lead to increased accuracy in the operation of the proposed system. Reliable control and monitor indoor air quality would help safety professionals develop policies and regulations in ensuring good indoor air quality and protect sensitive groups, and the staff working in hospitals, nursing homes, and other healthcare facilities; thereby minimizing negative airborne health effects.",
    link: "https://doi.org/10.1016/j.asoc.2022.108658",
    publicher: "1568-4946/© 2022 Elsevier B.V. All rights reserved."
  },
  {
    id: 3,
    image: "./images/8.jpg",
    date: "20 Jun, 2021",
    title_one: "The Detection of Taxpayers with False Invoices using Data Mining Techniques.",
    desc_one: "Abolfazl Ghorbani, Fatemeh Davoodi, Kamran Layeghi",
    title_two: "ABSTRACT",
    desc_two: "In this article, indicators are presented that can be used to identify those users who are suspected of providing fake invoices. With the help of data mining methods, it is possible to find out the forms that are related to the insertion of incorrect financial and operational information to avoid paying taxes or reduce them. In this research, first, using clustering algorithms [1] such as self-organizing networks [2] and neural networks [3], groups of taxpayers who have similar behavior were identified, and then using decision tree algorithms, neural networks [4] and Bayesian networks [5] started to identify variables related to fraudulent behavior, related behavioral patterns and detect cases of fraud. The statistical population of this research is economic enterprises including companies, factories, workshops in the city and province of Tehran. The results of the data mining methods of this research distinguished the variables that should be considered in the case of small, large and medium economic enterprises for auditing, and the neural network model with an accuracy of 92% on the training data and an accuracy of 88% on the validation data. And with an accuracy rate of 89% on the test data, he was able to discover tax evasion.",
    title_three: "Conclusions and future work.",
    desc_three: "The results of the data mining methods of this research distinguished the variables that should be considered in the case of small, large, and medium economic enterprises for auditing, and the neural network model with an accuracy of 92% on the training data with an accuracy of 88%. On validation data and with an accuracy of 89% on test data, he was able to discover tax evasion. In recent years, data mining and artificial intelligence techniques have been incorporated into audit planning activities, mainly to detect patterns of tax fraud or evasion, and are used by tax authorities for specific purposes (US Accountability Office, 2004). Economic Development and Cooperation Organization, 2004). In the Australian Taxation Office, the acceptance program is prepared and developed based on a risk identification model that uses statistical and data mining techniques to compare, find relationships and patterns of logistic regression 1, decision trees and machine support 2 (US Government Accountability Office, 2004; US Government Accountability Office, 2008). Canada, for its part, uses neural networks and decision trees to identify the characteristics of taxpayers who evade paying taxes or commit fraud, based on the results of past audits and in order to identify patterns of non-acceptance or evasion. Taxes have been formed.",
    link: "https://www.noormags.ir/view/fa/creator/844037",
    publicher: "Publisher: Iranian National Tax Administration (INTA)."
  },
]
export default BlogApi
